version: '3'
services:
  app:
    container_name: app2
    build:
      context: .
      dockerfile: Dockerfile
    image: app2:latest
    entrypoint: ./run.sh
    expose:
      - 8080
    ports:
      - 8080:8080
