version: '3.2'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    image: mysql_with_many_dbs  
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      # MYSQL_DATABASE: mydb 
      MYSQL_USER: user
      MYSQL_PASSWORD: password
