version: '2'

services:
   db:
     image: docker_image_name  
     restart: always
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: mydb 
       MYSQL_USER: user
       MYSQL_PASSWORD: password
