DROP DATABASE IF EXISTS mydb;
   
CREATE DATABASE IF NOT EXISTS mydb;
 
USE mydb;
 
CREATE TABLE MY_TABLE(
	  ID INT NOT NULL auto_increment, 
	  NAME VARCHAR(50) NOT NULL, 
	  PRIMARY KEY (ID)
);
 
DESC MY_TABLE;
 
