version: '3.1'

services:
  db:
    image: mysql 
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASES: db_name
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080